name: Publish docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - base.Dockerfile

jobs:
  publish:
    name: Publish docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker
        run: docker build -f base.Dockerfile -t ghcr.io/rikudousage/lemmy-auto-tldr-bot:base --label "org.opencontainers.image.source=https://github.com/RikudouSage/LemmyAutoTldrBot" --label "org.opencontainers.image.licenses=MIT" .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        env:
          VERSION: ${{ steps.extract_version.outputs.result }}
        run: docker push ghcr.io/rikudousage/lemmy-auto-tldr-bot:base
