name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LEMMY_PASSWORD: ${{ secrets.LEMMY_PASSWORD }}
      LEMMY_USER: ${{ secrets.LEMMY_USER }}
      AWS_REGION: eu-central-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            base:
              - base.Dockerfile
      - name: Wait on base build
        if: steps.changed_files.outputs.base_any_changed == 'true'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: Push to registry
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install serverless
        run: |
          yarn global add serverless@3
          yarn install
      - name: Login to ECR
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query "Account" --output text).dkr.ecr.$AWS_REGION.amazonaws.com
      - name: Deploy app
        run: serverless deploy --stage prod --verbose --region $AWS_REGION
