name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LEMMY_PASSWORD: ${{ secrets.LEMMY_PASSWORD }}
      LEMMY_USER: ${{ secrets.LEMMY_USER }}
      AWS_REGION: eu-central-1
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install serverless
        run: yarn global add serverless@3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy app
        run: serverless deploy --stage prod --verbose --region $AWS_REGION
